FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Asia/Tokyo

RUN apt update&&\
    apt upgrade -y

RUN apt install -y build-essential \
    cmake \
    ninja-build \
    clang-format \
    clang-tidy \
    ccache \
    clangd\
    git && \
    apt clean && \
    rm -rf /var/lib/apt/lists/*

RUN git clone https://github.com/google/googletest.git /opt/googletest && \
    cd /opt/googletest && \
    cmake -S . -B build -G Ninja && \
    ninja -C build install

RUN git clone https://gitlab.com/libeigen/eigen.git /opt/eigen && \
    cd /opt/eigen && \
    cmake -S . -B build -G Ninja && \
    ninja -C build install && \
    rm -rf /opt/eigen

ENV CC="ccache gcc"
ENV CXX="ccache g++"
RUN ccache --max-size=5G

RUN useradd -m vscode && \
    echo "vscode ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers



